#!/bin/bash
USAGE="Usage: $0 IP1 IP2 IP3 ..."

if [ "$#" == "0" ]; then
        echo "$USAGE"
        exit 1
fi


i=0
for host in "$@" 
do
	if [ "$host" = "$1" ]
	then
		sudo rm -rf ../data/cassandra/*
		docker rm cassandra-node
		sleep 15
		docker run --name cassandra-node -v /home/student/repo_a2group47/data/cassandra:/var/lib/cassandra -d -e CASSANDRA_BROADCAST_ADDRESS=$1 -p 7000:7000 -p 9042:9042 cassandra
		docker stack rm urlshortner
		docker swarm leave --force
		docker swarm init --advertise-addr $host
	else	
		if [ "$i" -lt 2 ]
		then
			CMD="docker rm cassandra-node; sleep 15;"
			ssh $host "$CMD docker run --name cassandra-node -v /home/student/repo_a2group47/data/cassandra:/var/lib/cassandra -d -e CASSANDRA_BROADCAST_ADDRESS=$host -p 7000:7000 -p 9042:9042 -e CASSANDRA_SEEDS=$1 cassandra"
		fi
		./addNode $host
		((i=i+1))
	fi
done
docker stack deploy -c docker-compose.yml urlshortner
